spring:
  application:
    name: travelhub
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

neo4j:
  uri: bolt://neo4j:7687
  authentication:
    username: neo4j
    password: password
